services:
  - type: web
    name: voice-widget
    runtime: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ASSISTANT_ID
        sync: false
      - key: FLASK_SECRET
        sync: false
    region: frankfurt
    healthCheckPath: /